# https://github.com/hvr/multi-ghc-travis/blob/master/.travis.yml
language: c

env:
 - CABALVER=2.0 GHCVER=8.2.2 FLAGS=-fdocs HAPPYVER=1.19.9 MTL=
 - CABALVER=2.0 GHCVER=8.2.2 FLAGS=-f-docs HAPPYVER=1.19.9 MTL=
 - CABALVER=2.2 GHCVER=8.4.3 FLAGS=-fdocs HAPPYVER=1.19.9 MTL=
 - CABALVER=2.2 GHCVER=8.4.3 FLAGS=-f-docs HAPPYVER=1.19.9 MTL=
 - CABALVER=2.2 GHCVER=8.6.1 FLAGS=-fdocs HAPPYVER=1.19.9 MTL=
 - CABALVER=2.2 GHCVER=8.6.1 FLAGS=-f-docs HAPPYVER=1.19.9 MTL=

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install --force-yes cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version)"
 - travis_retry cabal update
 # install latest version of deps within sandbox
 - cabal sandbox init
 # end
 - cabal install $MTL happy-$HAPPYVER
 - cabal install --only-dependencies --enable-tests $FLAGS

script:
 - cabal configure --enable-tests $FLAGS
 - cabal build
 - cabal test
 - cabal sdist
